### PR TITLE
Update Firefox icon

### PR DESCRIPTION
**Pull request by refi64**
At this point half the Firefox-related files are in the repo anyway, the icon isn't a huge addition. It's the SVG, so it's scalable as per the new GNOME icon preferences (and looks a lot better in the apps menu as well).

### CODE REVIEW

**Review by andrunko — CHANGES_REQUESTED** [review]
Changes look good but I would prefer if we do the [same as upstream](https://hg.mozilla.org/projects/maple/file/tip/taskcluster/docker/firefox-flatpak/flatpak.json.in#l63) here and install the icons shipped with the firefox tarball, unless there is a strong reason not to (the provided icons support several sizes, so it should be Ok to not be scalable).

Fwiw it seems you forgot to commit the .svg or am I missing something?

**Comment by refi64** [comment]
~~Ack I did forget, I guess I can do the PNGs, it just seemed a bit pointless.~~ **EDIT:** Sorry I misread what you said, the reason we can't do that is because Firefox is downloaded as extra-data, so the icons wouldn't be available until install time, whereas at least one icon needs to be present at build time for the desktop file.

**Comment by andrunko** [comment]
> ~Ack I did forget, I guess I can do the PNGs, it just seemed a bit pointless.~ **EDIT:** Sorry I misread what you said, the reason we can't do that is because Firefox is downloaded as extra-data, so the icons wouldn't be available until install time, whereas at least one icon needs to be present at build time for the desktop file.

I see, makes sense, lets go with the the svg then - please update the PR with the .svg and I will merge.

**Comment by refi64** [comment]
@andrunko Done.

**Review by andrunko — APPROVED** [review]

**Pull request merged**
